- name: Deploy app
  hosts: appinstances
  become: true
  tasks: 
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
        
    - name: Install package ubuntu
      become: true
      apt: 
        name: ['openjdk-8-jdk']
        state: present
       
    - name: Copy jar file
      copy:
        src: '{{ JAR_FILE }}'
        dest: /app/eureka/build/app.jar
        owner: tranphuochiep1997
        group: tranphuochiep1997
        mode: '777'    
        
    - name: Copy systemd service file to server
      copy:
        src: eureka.service
        dest: /etc/systemd/system
        
    - name: Restart service
      systemd:
        name: eureka
        state: restarted
        enabled: yes
      